### ISSUE TITLE
Running tests using FailGood::runAllTests or using the auto-test feature fails on Windows

### ISSUE THREAD

**Issue by mervyn-mccreight** [failgood/failgood#114]
## Actual behavior

There are two tests of the failgood suite failing when getting run on my windows machine.

The first one is `test finder - can find Test classes` and it fails with the following exception:

```
Illegal char <:> at index 2: /C:/Users/censored/private/kotlin/failgood/failgood/build/classes/kotlin/test/
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/censored/private/kotlin/failgood/failgood/build/classes/kotlin/test/
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at failgood.FailGood.findTestClasses(FailGood.kt:136)
	at failgood.FailGood.findTestClasses$default(FailGood.kt:130)
	at failgood.TestFinderTest$context$1$1.invokeSuspend(TestFinderTest.kt:15)
	at failgood.TestFinderTest$context$1$1.invoke(TestFinderTest.kt)
	at failgood.TestFinderTest$context$1$1.invoke(TestFinderTest.kt)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invokeSuspend(ContextExecutor.kt:146)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invoke(ContextExecutor.kt)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invoke(ContextExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at failgood.internal.ContextExecutor$ContextVisitor.executeTest(ContextExecutor.kt:143)
	at failgood.internal.ContextExecutor$ContextVisitor.access$executeTest(ContextExecutor.kt:68)
	at failgood.internal.ContextExecutor$ContextVisitor$test$2.invokeSuspend(ContextExecutor.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

The second one is `the ContextFinder - test filtering - supports a classpathRootSelector with a package filter`:

```
Illegal char <:> at index 2: /C:/Users/censored/private/kotlin/failgood/failgood/build/classes/kotlin/test/
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/censored/private/kotlin/failgood/failgood/build/classes/kotlin/test/
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at failgood.junit.ContextFinderTest$context$1$3$1.invokeSuspend(ContextFinderTest.kt:46)
	at failgood.junit.ContextFinderTest$context$1$3$1.invoke(ContextFinderTest.kt)
	at failgood.junit.ContextFinderTest$context$1$3$1.invoke(ContextFinderTest.kt)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invokeSuspend(ContextExecutor.kt:146)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invoke(ContextExecutor.kt)
	at failgood.internal.ContextExecutor$ContextVisitor$executeTest$2.invoke(ContextExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at failgood.internal.ContextExecutor$ContextVisitor.executeTest(ContextExecutor.kt:143)
	at failgood.internal.ContextExecutor$ContextVisitor.access$executeTest(ContextExecutor.kt:68)
	at failgood.internal.ContextExecutor$ContextVisitor$test$2.invokeSuspend(ContextExecutor.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Expected behavior
All tests run successfully on a windows machine

## How to reproduce
I called `gradle check` of the `failgood` project to run the tests.

**Comment by christophsturm** [comment]
does this only affect running the test suite on windows or does it also affect using failgood on windows?

**Comment by mervyn-mccreight** [comment]
I did a test in an example project containing only tests of all variants of test definitions I could find in Failgood (class, toplevel, class with list of contexts, object) and a gradle check ran successfully in this example project. This ran successfully. I have to say I used the JUnit integration there. I'll try running the same tests without JUnit using FailGood directly as well.

**Comment by mervyn-mccreight** [comment]
Using `FailGood::runAllTests` or the auto-test functionality runs into the same problem, so I would say this is a general problem using FailGood on windows, but it only affects running tests using FailGood directly and not using the JUnit-integration.

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/censored/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at failgood.FailGood.findTestClasses(FailGood.kt:136)
	at failgood.FailGood.findTestClasses$default(FailGood.kt:130)
	at failgood.FailGood.runAllTests(FailGood.kt:197)
	at failgood.FailGood.runAllTests$default(FailGood.kt:196)
	at org.example.RunUsingFailGoodKt.main(runUsingFailGood.kt:6)
	at org.example.RunUsingFailGoodKt$main$2.invoke(runUsingFailGood.kt)
	at org.example.RunUsingFailGoodKt$main$2.invoke(runUsingFailGood.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at org.example.RunUsingFailGoodKt.main(runUsingFailGood.kt)

Process finished with exit code 1
```

I'd say the root cause is in `FailGood::findTestClasses` and this is why the test of this function is failing when running the failgood test suite. This functions seems only to be used when running tests using FailGood directly, but not when using the JUnit-integration.

**Comment by mervyn-mccreight** [comment]
IMO this should be labeled as a bug (if we are using labels here)
