### ISSUE TITLE
runAllTests does not work on windows

### ISSUE THREAD

**Issue by christophsturm** [failgood/failgood#30]
workaround is to use the junit engine via gradle or idea
```
exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/.../build/classes/kotlin/test/
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
at failgood.FailGood.findTestClasses(FailGood.kt:174)
at failgood.FailGood.findTestClasses$default(FailGood.kt:168)
at failgood.FailGood.runAllTests(FailGood.kt:229)
at failgood.FailGood.runAllTests$default(FailGood.kt:228)
```

**Comment by christophsturm** [comment]
runAllTests is not supported on windows (and if you need it create a new issue with an up to date stacktrace)
